### ISSUE TITLE
Looking for Collaboration

### ISSUE THREAD

**Issue by AlexJJJChen** [chengqianma/WeatherQA#6]
Hi Hi, I am so excited to see that we share similar ideas on the application of AI in the field of meteorology! Actually, I see a great opportunity for us to collaborate and advance this exciting field together. Climate-Zoo and ClimateIQA are our initial trial in AI for Meteorology. In the future, we would like to utilize these research outcome in Climate Finance domain and support finance company. 

Unfortunately, I couldn't find your email address. Would it be possible to connect on WeChat? Alternatively, you can reach me at my email: jchen524@connect.hkust-gz.edu.cn. I am looking forward to discussing potential collaborations and sharing ideas.

**Comment by ZhanxiangHua** [comment]
Hi, it's nice to see someone also working on this type of project and we could potentially work together on something more interesting.
